// examples/cs2d/frontend/src/components/common/ConnectionStatus.vue
<template>
  <div
    class="connection-status"
    :class="{
      [connectionStatus]: true,
      minimized: isMinimized
    }"
    @click="toggleMinimized"
  >
    <div class="status-indicator">
      <div class="status-dot"></div>
    </div>
    
    <div v-if="!isMinimized" class="status-content">
      <div class="status-text">
        <span class="status-label">{{ statusText }}</span>
        <span v-if="latency" class="latency">{{ latency }}ms</span>
      </div>
      
      <div v-if="showDetails" class="status-details">
        <div class="detail-item">
          <span class="detail-label">Reconnect attempts:</span>
          <span class="detail-value">{{ reconnectAttempts }}</span>
        </div>
        <div v-if="lastConnected" class="detail-item">
          <span class="detail-label">Last connected:</span>
          <span class="detail-value">{{ formatTime(lastConnected) }}</span>
        </div>
      </div>
      
      <div v-if="connectionStatus === 'disconnected'" class="status-actions">
        <button @click.stop="reconnect" class="reconnect-btn">
          Reconnect
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useWebSocketStore } from '@/stores/websocket'
import { useWebSocket } from '@/services/websocket'

const wsStore = useWebSocketStore()
const ws = useWebSocket()

const isMinimized = ref(false)
const showDetails = ref(false)

const connectionStatus = computed(() => wsStore.connectionStatus.status)
const latency = computed(() => wsStore.latency)
const reconnectAttempts = computed(() => wsStore.reconnectAttempts)
const lastConnected = computed(() => wsStore.connectionStatus.lastConnected)

const statusText = computed(() => {
  switch (connectionStatus.value) {
    case 'connected':
      return 'Connected'
    case 'connecting':
      return 'Connecting...'
    case 'disconnected':
      return 'Disconnected'
    case 'error':
      return 'Connection Error'
    case 'offline':
      return 'Offline'
    default:
      return 'Unknown'
  }
})

function toggleMinimized() {
  isMinimized.value = !isMinimized.value
  if (!isMinimized.value) {
    showDetails.value = false
  }
}

function reconnect() {
  ws.connect()
}

function formatTime(date: Date): string {
  return date.toLocaleTimeString('en-US', {
    hour12: false,
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  })
}
</script>

<style scoped>
.connection-status {
  position: fixed;
  bottom: 1rem;
  right: 1rem;
  background: rgba(42, 42, 42, 0.95);
  border-radius: 8px;
  border: 1px solid var(--cs-border);
  backdrop-filter: blur(8px);
  cursor: pointer;
  transition: all 0.3s ease;
  z-index: 1000;
  min-width: 200px;
  max-width: 300px;
}

.connection-status:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
}

.connection-status.minimized {
  min-width: auto;
  width: 60px;
  height: 60px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.status-indicator {
  display: flex;
  align-items: center;
  padding: 1rem;
}

.connection-status.minimized .status-indicator {
  padding: 0;
}

.status-dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  margin-right: 0.75rem;
  transition: all 0.3s ease;
}

.connection-status.minimized .status-dot {
  margin-right: 0;
  width: 16px;
  height: 16px;
}

.connection-status.connected .status-dot {
  background: var(--cs-success);
  box-shadow: 0 0 8px rgba(46, 204, 113, 0.5);
}

.connection-status.connecting .status-dot {
  background: var(--cs-warning);
  animation: pulse 1.5s ease-in-out infinite;
}

.connection-status.disconnected .status-dot,
.connection-status.error .status-dot {
  background: var(--cs-danger);
}

.connection-status.offline .status-dot {
  background: var(--cs-gray);
}

.status-content {
  flex: 1;
  padding: 0 1rem 1rem 0;
}

.status-text {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.5rem;
}

.status-label {
  font-weight: 600;
  color: var(--cs-light);
  font-size: 0.9rem;
}

.latency {
  font-size: 0.8rem;
  color: var(--cs-gray);
  font-family: monospace;
}

.status-details {
  margin-top: 0.5rem;
  padding-top: 0.5rem;
  border-top: 1px solid var(--cs-border);
}

.detail-item {
  display: flex;
  justify-content: space-between;
  margin-bottom: 0.25rem;
  font-size: 0.8rem;
}

.detail-label {
  color: var(--cs-gray);
}

.detail-value {
  color: var(--cs-light);
  font-family: monospace;
}

.status-actions {
  margin-top: 0.75rem;
  padding-top: 0.75rem;
  border-top: 1px solid var(--cs-border);
}

.reconnect-btn {
  width: 100%;
  padding: 0.5rem;
  background: var(--cs-primary);
  border: none;
  border-radius: 4px;
  color: white;
  font-size: 0.8rem;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.3s ease;
}

.reconnect-btn:hover {
  background: var(--cs-secondary);
}

@keyframes pulse {
  0%, 100% {
    opacity: 1;
    transform: scale(1);
  }
  50% {
    opacity: 0.7;
    transform: scale(1.1);
  }
}

/* Mobile responsiveness */
@media (max-width: 768px) {
  .connection-status {
    bottom: 0.5rem;
    right: 0.5rem;
    min-width: 180px;
    max-width: 250px;
  }
  
  .connection-status.minimized {
    width: 50px;
    height: 50px;
  }
  
  .status-indicator {
    padding: 0.75rem;
  }
  
  .status-content {
    padding: 0 0.75rem 0.75rem 0;
  }
}
</style>

// examples/cs2d/frontend/src/components/common/ConnectionStatus.tsx
import { cn } from '@/utils/tailwind';
import React from 'react';
import { useState, useEffect, useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useWebSocketStore } from '@/stores/websocket'
import { useWebSocket } from '@/services/websocket'

interface ConnectionStatusProps {
  // TODO: Define props from Vue component
}

export const ConnectionStatus: React.FC<ConnectionStatusProps> = (props) => {
  const navigate = useNavigate();
  
  

const wsStore = useWebSocket()
const ws = useWebSocket()

const [isMinimized, set${this.capitalize("isMinimized")}] = useState(false)
const [showDetails, set${this.capitalize("showDetails")}] = useState(false)

const connectionStatus = useMemo(() => wsStore.connectionStatus.status, [])
const latency = useMemo(() => wsStore.latency, [])
const reconnectAttempts = useMemo(() => wsStore.reconnectAttempts, [])
const lastConnected = useMemo(() => wsStore.connectionStatus.lastConnected, [])

const statusText = useMemo(() => {
  switch (connectionStatus.value, []) {
    case 'connected':
      return 'Connected'
    case 'connecting':
      return 'Connecting...'
    case 'disconnected':
      return 'Disconnected'
    case 'error':
      return 'Connection Error'
    case 'offline':
      return 'Offline'
    default:
      return 'Unknown'
  }
})

function toggleMinimized() {
  isMinimized.value = !isMinimized.value
  if (!isMinimized.value) {
    showDetails.value = false
  }
}

function reconnect() {
  ws.connect()
}

function formatTime(date: Date): string {
  return date.toLocaleTimeString('en-US', {
    hour12: false,
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  })
}

  return (
    <div className="container mx-auto px-4">
      <div
    className="connection-status"
    className={{
      [connectionStatus]: true,
      minimized: isMinimized
    }}
    onClick={toggleMinimized}
  >
    <div className="status-indicator">
      <div className="status-dot"></div>)}
    </div>
    
    <div {!isMinimized && ( className="status-content">
      <div className="status-text">
        <span className="status-label">{statusText }</span>)}
        <span {latency && ( className="latency">{latency }ms</span>)}
      </div>
      
      <div {showDetails && ( className="status-details">
        <div className="detail-item">
          <span className="detail-label">Reconnect attempts:</span>)}
          <span className="detail-value">{reconnectAttempts }</span>)}
        </div>
        <div {lastConnected && ( className="detail-item">
          <span className="detail-label">Last connected:</span>)}
          <span className="detail-value">{formatTime(lastConnected) }</span>)}
        </div>
      </div>)}
      
      <div {connectionStatus === 'disconnected' && ( className="status-actions">
        <button @click.stop="reconnect" className="reconnect-btn hover:scale-105 active:scale-95 transition-transform">
          Reconnect
        </button>)}
      </div>
    </div>)}
  </div>
    </div>
  );
};

export default ConnectionStatus;
